version: '3.4'

services:
  wordservice:
    image: ${DOCKER_REGISTRY-}wordservice
    build:
      context: .
      dockerfile: WordService/Dockerfile
    depends_on:
      - db
    ports:
      - "9100:80"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"